<#
.SYNOPSIS
  Builds anonymous Apex from a use-case folder and runs it: Agentic prompts (JSON per skill),
  activate prompts, AI_Agent__c whose AI_Model__c is an AI_Connection__c with Type__c = Agentic,
  GPTfy (OpenAI) for AI_Prompt__c.AI_Connection__c, skills junction, intent skeleton, publish (Active).

.PARAMETER UseCasePath
  Folder containing *PromptCommand.json (or *command.json), AGENT_SYSTEM_PROMPT.txt, AGENT_DESCRIPTION.txt.
  AI_Prompt__c.Name = file name without extension, with trailing Prompt+Command or Command removed (case-insensitive).

.PARAMETER TargetOrg
  sf CLI alias or username (e.g. kalanithi@cloudcompliance.app.sgpt.uat)

.PARAMETER HandlerClass
  Apex class implementing AIAgenticInterface (executeMethod requestParam must match prompt Name / file stem).

.PARAMETER ExternalIdPrefix
  Stored on AI_Prompt__c.External_Id__c for idempotent updates (e.g. UC:IT_HELPDESK:).

.PARAMETER ConnectionName
  AI_Connection__c.Name for AI_Prompt__c only (default GPTfy OpenAI). Not used for the agent AI_Model__c.

.PARAMETER AgentModelConnectionName
  Preferred AI_Connection__c.Name where Type__c = 'Agentic' (default: Response API Agentic).
  If blank, or no row matches that Name with Type__c = Agentic, uses the latest AI_Connection__c with Type__c = 'Agentic'.

.PARAMETER DataMappingName
  AI_Data_Extraction_Mapping__c.Name for prompts.

.PARAMETER AgentName
  AI_Agent__c.Name (label).

.PARAMETER AgentDeveloperName
  Unique AI_Agent__c.Developer_Name__c.

.PARAMETER SkipIntents
  If set, do not create AI_Agent_Intent__c skeleton rows.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $UseCasePath,

    [Parameter(Mandatory = $true)]
    [string] $TargetOrg,

    [string] $HandlerClass = 'ITHelpdeskAgenticHandler',

    [string] $ExternalIdPrefix = 'UC:IT_HELPDESK:',

    [string] $ConnectionName = 'GPTfy (OpenAI)',

    [string] $AgentModelConnectionName = 'Response API Agentic',

    [string] $DataMappingName = 'Account 360 view - GPTfy',

    [string] $AgentName = 'IT Helpdesk Agent (Pipeline)',

    [string] $AgentDeveloperName = 'IT_Helpdesk_Pipeline',

    [string] $FullConfigPath,

    [switch] $SkipIntents
)

function ConvertTo-ApexSingleQuoted([string] $text) {
    if ($null -eq $text) { return "''" }
    $t = $text -replace '\\', '\\\\' -replace "'", "''" -replace "`r`n", '\n' -replace "`n", '\n' -replace "`r", '\n'
    return "'" + $t + "'"
}

$resolved = Resolve-Path -Path $UseCasePath -ErrorAction Stop
$jsonFiles = Get-ChildItem -Path $resolved -Filter '*.json' -File |
    Where-Object {
        $bn = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
        $bn -match '(?i)(_prompt)?command$'
    } | Sort-Object Name
if ($jsonFiles.Count -eq 0) {
    throw "No prompt-command JSON under $resolved (basename must end with _PromptCommand, PromptCommand, _command, or Command)"
}

$sysPath = Join-Path $resolved 'AGENT_SYSTEM_PROMPT.txt'
$descPath = Join-Path $resolved 'AGENT_DESCRIPTION.txt'
if (-not (Test-Path $sysPath)) { throw "Missing AGENT_SYSTEM_PROMPT.txt" }
if (-not (Test-Path $descPath)) { throw "Missing AGENT_DESCRIPTION.txt" }

$systemPrompt = Get-Content -LiteralPath $sysPath -Raw -Encoding UTF8
$agentDescription = Get-Content -LiteralPath $descPath -Raw -Encoding UTF8

$skillEntries = @()
foreach ($f in $jsonFiles) {
    # Prompt Name = file name without extension, minus trailing "Command" (optional "_Prompt" before it).
    # e.g. create_case_for_contact_PromptCommand -> create_case_for_contact ; foo_command -> foo
    $base = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
    $stem = $base -replace '(?i)(_prompt)?command$', ''
    $stem = $stem.TrimEnd('_')
    if ([string]::IsNullOrWhiteSpace($stem)) { continue }
    $raw = Get-Content -LiteralPath $f.FullName -Raw -Encoding UTF8
    $obj = $raw | ConvertFrom-Json
    $compact = ($obj | ConvertTo-Json -Compress -Depth 30)
    $skillEntries += [pscustomobject]@{ Key = $stem; Json = $compact }
}

$mapLines = @()
foreach ($e in $skillEntries) {
    $lit = ConvertTo-ApexSingleQuoted $e.Json
    $mapLines += "        cmdJson.put('" + $e.Key + "', " + $lit + ");"
}
$mapBlock = $mapLines -join "`n"

$apexSys = ConvertTo-ApexSingleQuoted $systemPrompt
$apexDesc = ConvertTo-ApexSingleQuoted $agentDescription
$apexConn = ConvertTo-ApexSingleQuoted $ConnectionName
$apexAgentModelConn = ConvertTo-ApexSingleQuoted $AgentModelConnectionName
$apexMapName = ConvertTo-ApexSingleQuoted $DataMappingName
$apexHandler = ConvertTo-ApexSingleQuoted $HandlerClass
$apexPrefix = ConvertTo-ApexSingleQuoted $ExternalIdPrefix
$apexAgentName = ConvertTo-ApexSingleQuoted $AgentName
$apexAgentDev = ConvertTo-ApexSingleQuoted $AgentDeveloperName

$apexBody = @"
// Generated by Deploy-GptfyUseCasePipeline.ps1 - do not edit by hand
String HANDLER_CLASS = $apexHandler;
String UC_PREFIX = $apexPrefix;
String targetAgentName = $apexAgentName;
String agentDevName = $apexAgentDev;

Id promptConnId;
for (String connName : new List<String>{ $apexConn, 'OpenAI-4/ChatGPT', 'GPTfy' }) {
    List<AI_Connection__c> conns = [
        SELECT Id FROM AI_Connection__c WHERE Name = :connName LIMIT 1
    ];
    if (!conns.isEmpty()) {
        promptConnId = conns[0].Id;
        break;
    }
}
if (promptConnId == null) {
    System.assert(false, 'No AI_Connection__c for prompts (try GPTfy OpenAI / OpenAI fallbacks)');
}

String preferredAgenticConnName = $apexAgentModelConn;
List<AI_Connection__c> agentModelRows = new List<AI_Connection__c>();
if (String.isNotBlank(preferredAgenticConnName)) {
    agentModelRows = [
        SELECT Id FROM AI_Connection__c
        WHERE Type__c = 'Agentic' AND Name = :preferredAgenticConnName
        LIMIT 1
    ];
}
if (agentModelRows.isEmpty()) {
    agentModelRows = [
        SELECT Id FROM AI_Connection__c
        WHERE Type__c = 'Agentic'
        ORDER BY LastModifiedDate DESC
        LIMIT 1
    ];
}
if (agentModelRows.isEmpty()) {
    System.assert(false, 'No AI_Connection__c with Type__c = Agentic for AI_Agent__c.AI_Model__c');
}
Id agentModelId = agentModelRows[0].Id;

List<AI_Data_Extraction_Mapping__c> maps = [
    SELECT Id FROM AI_Data_Extraction_Mapping__c WHERE Name = $apexMapName LIMIT 1
];
if (maps.isEmpty()) { System.assert(false, 'No AI_Data_Extraction_Mapping__c named ' + $apexMapName); }
Id mapId = maps[0].Id;

Map<String, String> cmdJson = new Map<String, String>();
$mapBlock

Set<String> extKeys = new Set<String>();
for (String k : cmdJson.keySet()) {
    extKeys.add(UC_PREFIX + k);
}

List<AI_Prompt__c> existing = [
    SELECT Id, External_Id__c FROM AI_Prompt__c WHERE External_Id__c IN :extKeys
];
Map<String, Id> extToId = new Map<String, Id>();
for (AI_Prompt__c p : existing) {
    extToId.put(p.External_Id__c, p.Id);
}

List<AI_Prompt__c> toUpsert = new List<AI_Prompt__c>();
for (String k : cmdJson.keySet()) {
    String ext = UC_PREFIX + k;
    AI_Prompt__c pr = new AI_Prompt__c();
    if (extToId.containsKey(ext)) {
        pr.Id = extToId.get(ext);
    }
    pr.Name = k.length() > 80 ? k.substring(0, 80) : k;
    pr.Type__c = 'Agentic';
    pr.Status__c = 'Draft';
    pr.AI_Connection__c = promptConnId;
    pr.AI_Data_Extraction_Mapping__c = mapId;
    pr.Prompt_Command__c = cmdJson.get(k);
    pr.Agentic_Function_Class__c = HANDLER_CLASS;
    pr.External_Id__c = ext;
    toUpsert.add(pr);
}
upsert toUpsert;

List<AI_Prompt__c> activated = [
    SELECT Id FROM AI_Prompt__c WHERE External_Id__c IN :extKeys
];
for (AI_Prompt__c p : activated) {
    p.Status__c = 'Active';
}
update activated;

AI_Agent__c agent;
List<AI_Agent__c> agExisting = [
    SELECT Id FROM AI_Agent__c WHERE Developer_Name__c = :agentDevName LIMIT 1
];
if (agExisting.isEmpty()) {
    agent = new AI_Agent__c(
        Name = targetAgentName,
        Developer_Name__c = agentDevName,
        AI_Model__c = agentModelId,
        System_Prompt__c = $apexSys,
        Description__c = $apexDesc,
        Status__c = 'Draft'
    );
    insert agent;
} else {
    agent = agExisting[0];
    agent.AI_Model__c = agentModelId;
    agent.System_Prompt__c = $apexSys;
    agent.Description__c = $apexDesc;
    update agent;
}

String likePat = UC_PREFIX + '%';
delete [
    SELECT Id FROM AI_Agent_Skill__c
    WHERE AI_Agent__c = :agent.Id
    AND AI_Prompt__c IN (SELECT Id FROM AI_Prompt__c WHERE External_Id__c LIKE :likePat)
];

List<AI_Agent_Skill__c> skills = new List<AI_Agent_Skill__c>();
for (AI_Prompt__c p : activated) {
    skills.add(new AI_Agent_Skill__c(AI_Agent__c = agent.Id, AI_Prompt__c = p.Id));
}
insert skills;

agent.Status__c = 'Active';
update agent;

System.debug('PIPELINE OK: Agent ' + agent.Id + ' Active; prompts: ' + activated.size());
"@

$outFile = Join-Path $env:TEMP ("gptfy_pipeline_" + [Guid]::NewGuid().ToString('N') + ".apex")
[System.IO.File]::WriteAllText($outFile, $apexBody, [System.Text.UTF8Encoding]::new($false))
Write-Host "Running anonymous Apex: $outFile"
sf apex run --file $outFile --target-org $TargetOrg
$exit = $LASTEXITCODE
Remove-Item -LiteralPath $outFile -Force -ErrorAction SilentlyContinue
if ($exit -ne 0) { exit $exit }

if (-not $SkipIntents) {
    $repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
    $tpl = if ($FullConfigPath) { $FullConfigPath } else { Join-Path $repoRoot 'use-cases\IT_Helpdesk_Agent\FullConfig_AnonymousApex.apex' }
    if (-not (Test-Path -LiteralPath $tpl)) {
        Write-Warning "Intent skeleton skipped: file not found: $tpl (use -FullConfigPath or -SkipIntents)"
    } else {
        $fc = Get-Content -LiteralPath $tpl -Raw -Encoding UTF8
        $replacementLine = 'String targetAgentName = ''' + ($AgentName -replace '''', '''''') + ''';'
        $fc2 = $fc -replace "String targetAgentName = 'IT Helpdesk Agent';", $replacementLine
        $intentTmp = Join-Path $env:TEMP ('gptfy_intents_' + [Guid]::NewGuid().ToString('N') + '.apex')
        [System.IO.File]::WriteAllText($intentTmp, $fc2, [System.Text.UTF8Encoding]::new($false))
        Write-Host "Running intent FullConfig for agent name: $AgentName"
        sf apex run --file $intentTmp --target-org $TargetOrg
        $exit2 = $LASTEXITCODE
        Remove-Item -LiteralPath $intentTmp -Force -ErrorAction SilentlyContinue
        if ($exit2 -ne 0) { exit $exit2 }
    }
}
