import type { GeneratedBundle } from "./generation-types";
import { defaultIntentDeployPlan } from "./intent-deploy-types";

const META_XML = `<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>59.0</apiVersion>
    <status>Active</status>
</ApexClass>
`;

function resolveAgenticInterfaceSymbol(gptfyNamespace?: string): string {
  const raw = gptfyNamespace?.trim();
  if (!raw) return "AIAgenticInterface";

  const noSuffix = raw.replace(/__$/, "");
  if (!noSuffix) return "AIAgenticInterface";

  // Example: ccai_qa__ -> ccai__qa_AIAgenticInterface (as required by target orgs).
  const normalizedNs = noSuffix.includes("_")
    ? noSuffix.replace("_", "__")
    : noSuffix;
  return `${normalizedNs}_AIAgenticInterface`;
}

function buildHandlerApex(
  handlerClass: string,
  logPrefix: string,
  gptfyNamespace?: string
): string {
  const agenticInterface = resolveAgenticInterfaceSymbol(gptfyNamespace);
  return `/**
 * Generated by GPTfy Agent Generator (template). Replace stub logic with your use case.
 * Implements ${agenticInterface} — skill name must match AI Prompt Name exactly.
 */
global with sharing class ${handlerClass} implements ${agenticInterface} {

    private static final String LOG_PFX = '${logPrefix}';

    private void logDiag(String msg) {
        System.debug(LoggingLevel.ERROR, LOG_PFX + ' | ' + msg);
    }

    private String err(String msg) {
        logDiag('ERROR | ' + msg);
        return JSON.serialize(new Map<String, Object>{
            'success' => false,
            'status' => 'errored',
            'message' => msg
        });
    }

    private String ok(Map<String, Object> body) {
        body.put('success', true);
        body.put('status', 'ok');
        return JSON.serialize(body);
    }

    global String executeMethod(String requestParam, Map<String, Object> parameters) {
        try {
            if (parameters == null) {
                parameters = new Map<String, Object>();
            }
            logDiag('executeMethod | skill=' + requestParam);
            switch on requestParam {
                when 'health_Check_Agent' {
                    return healthCheck(parameters);
                }
                when else {
                    return err('Unsupported skill: ' + requestParam + '. Use health_Check_Agent.');
                }
            }
        } catch (Exception ex) {
            logDiag('EXCEPTION | ' + ex.getMessage());
            return err(ex.getMessage());
        }
    }

    private String healthCheck(Map<String, Object> parameters) {
        return ok(new Map<String, Object>{
            'message' => 'Handler is deployed and reachable. Replace this skill with your use-case logic.',
            'organizationId' => UserInfo.getOrganizationId(),
            'userId' => UserInfo.getUserId(),
            'note' => 'Add PromptCommand JSON files and switch cases matching each AI Prompt Name.'
        });
    }
}
`;
}

const HEALTH_PROMPT_JSON = {
  type: "object",
  required: [] as string[],
  properties: {
    echo: {
      type: "string",
      description:
        "OPTIONAL. Any short string from the user for testing. This field is OPTIONAL.",
    },
  },
};

function buildFullConfigStub(
  agentName: string,
  handlerClass: string
): string {
  return `// Intent skeleton stub — replace with real intents or use Data Loader templates.
// Pipeline replaces targetAgentName line when you run Deploy-GptfyUseCasePipeline.ps1
String targetAgentName = '${agentName.replace(/'/g, "\\'")}';
// TODO: insert AI_Agent_Intent__c / AI_Intent_Action__c rows for agent named targetAgentName
// Handler: ${handlerClass}
System.debug('FullConfig stub: configure intents for ' + targetAgentName);
`;
}

export function buildTemplateBundle(
  params: GeneratedBundle["parameters"],
  useCase: string,
  notes?: string,
  orgContext?: { gptfyNamespace?: string }
): GeneratedBundle {
  const logPrefix = params.handlerClass.replace(/Handler$/, "").substring(0, 8).toUpperCase();
  const handlerApex = buildHandlerApex(
    params.handlerClass,
    logPrefix,
    orgContext?.gptfyNamespace
  );

  const promptFile = `health_Check_Agent_PromptCommand.json`;
  const promptContent = JSON.stringify(HEALTH_PROMPT_JSON, null, 2);

  const agentDescription = `${params.agentName}: ${useCase.slice(0, 200)}${useCase.length > 200 ? "…" : ""}`;

  const agentSystemPrompt = `You are ${params.agentName}.

CORE RESPONSIBILITIES:
- Help users according to this use case:
${useCase}
${notes ? `\nNOTES:\n${notes}\n` : ""}
- For any Salesforce data change or query, you MUST call the correct agentic tool and only claim success if the tool response has success: true.

CRITICAL:
- NEVER claim a record was created/updated or data retrieved unless the tool response confirms it.
- Start by calling health_Check_Agent once if you need to verify the integration is live.

LIMITATIONS:
- You only have the health_Check_Agent skill until more PromptCommand JSON files and handler methods are added in Salesforce.
`;

  const intentsConfigMd = `# ${params.agentName} — Intents (starter)

**Agent:** ${params.agentName}
**Total Intents:** 2 (minimum starter)

## ${params.agentDeveloperName}_greeting
**Trigger:** User opens chat or says hello.
**Actions:** Canned Response (welcome).

## ${params.agentDeveloperName}_out_of_scope
**Trigger:** User asks for something outside this agent's skills.
**Actions:** Canned Response (polite redirect).

> Extend with domain intents per docs/INTENT_ACTION_FRAMEWORK_GUIDE.md
`;

  const specMarkdown = `# Generated bundle (template)

## Use case
${useCase}

## Parameters
| Field | Value |
|-------|-------|
| Agent | ${params.agentName} |
| Developer name | ${params.agentDeveloperName} |
| Handler | ${params.handlerClass} |
| External prefix | ${params.externalIdPrefix} |

## Deploy steps
1. Copy \`classes/${params.handlerClass}.cls\` into \`force-app/main/default/classes/\` and deploy.
2. Copy \`use-cases/${params.agentDeveloperName}/\` into your repo.
3. Run \`Deploy-GptfyUseCasePipeline.ps1\` with matching parameters.

Namespace: package subscribers use \`ccai__\` / \`ccai_qa__\` on objects; unpackaged orgs often have no prefix.
`;

  return {
    version: 1,
    source: "template",
    parameters: params,
    handlerApex,
    handlerMetaXml: META_XML,
    agentDescription,
    agentSystemPrompt,
    intentsConfigMd,
    promptCommands: [{ fileName: promptFile, content: promptContent }],
    specMarkdown,
    fullConfigStubApex: buildFullConfigStub(params.agentName, params.handlerClass),
    intentDeployPlan: defaultIntentDeployPlan(
      params.agentDeveloperName,
      params.agentName
    ),
  };
}
