import type { GeneratedBundle } from "./generation-types";
import { defaultIntentDeployPlan } from "./intent-deploy-types";

const META_XML = `<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>59.0</apiVersion>
    <status>Active</status>
</ApexClass>
`;

function resolveAgenticInterfaceSymbol(gptfyNamespace?: string): string {
  const raw = gptfyNamespace?.trim();
  if (!raw) return "AIAgenticInterface";

  const noSuffix = raw.replace(/__$/, "");
  if (!noSuffix) return "AIAgenticInterface";

  // Apex class namespaces are dot-qualified, e.g. ccai_qa.AIAgenticInterface
  return `${noSuffix}.AIAgenticInterface`;
}

function buildHandlerApex(
  handlerClass: string,
  logPrefix: string,
  skillName: string,
  gptfyNamespace?: string
): string {
  const agenticInterface = resolveAgenticInterfaceSymbol(gptfyNamespace);
  return `/**
 * Generated by GPTfy Agent Generator (template). Replace stub logic with your use case.
 * Implements ${agenticInterface} — skill name must match AI Prompt Name exactly.
 */
global with sharing class ${handlerClass} implements ${agenticInterface} {

    private static final String LOG_PFX = '${logPrefix}';

    private void logDiag(String msg) {
        System.debug(LoggingLevel.ERROR, LOG_PFX + ' | ' + msg);
    }

    private String err(String msg) {
        logDiag('ERROR | ' + msg);
        return JSON.serialize(new Map<String, Object>{
            'success' => false,
            'status' => 'errored',
            'message' => msg
        });
    }

    private String ok(Map<String, Object> body) {
        body.put('success', true);
        body.put('status', 'ok');
        return JSON.serialize(body);
    }

    global String executeMethod(String requestParam, Map<String, Object> parameters) {
        try {
            if (parameters == null) {
                parameters = new Map<String, Object>();
            }
            logDiag('executeMethod | skill=' + requestParam);
            switch on requestParam {
                when '${skillName}' {
                    return healthCheck(parameters);
                }
                when else {
                    return err('Unsupported skill: ' + requestParam + '. Use ${skillName}.');
                }
            }
        } catch (Exception ex) {
            logDiag('EXCEPTION | ' + ex.getMessage());
            return err(ex.getMessage());
        }
    }

    private String healthCheck(Map<String, Object> parameters) {
        return ok(new Map<String, Object>{
            'message' => 'Handler is deployed and reachable. Replace this skill with your use-case logic.',
            'organizationId' => UserInfo.getOrganizationId(),
            'userId' => UserInfo.getUserId(),
            'note' => 'Add PromptCommand JSON files and switch cases matching each AI Prompt Name.'
        });
    }
}
`;
}

const HEALTH_PROMPT_JSON = {
  type: "object",
  required: [] as string[],
  properties: {
    echo: {
      type: "string",
      description:
        "OPTIONAL. Any short string from the user for testing. This field is OPTIONAL.",
    },
  },
};

function buildFullConfigStub(
  agentName: string,
  handlerClass: string
): string {
  return `// Intent skeleton stub — replace with real intents or use Data Loader templates.
// Pipeline replaces targetAgentName line when you run Deploy-GptfyUseCasePipeline.ps1
String targetAgentName = '${agentName.replace(/'/g, "\\'")}';
// TODO: insert AI_Agent_Intent__c / AI_Intent_Action__c rows for agent named targetAgentName
// Handler: ${handlerClass}
System.debug('FullConfig stub: configure intents for ' + targetAgentName);
`;
}

function buildTemplateSampleQueries(skillName: string, intentNames: string[]): string[] {
  const q: string[] = [];
  q.push(`Use skill ${skillName} to run a health check and summarize the result.`);
  for (const intent of intentNames) {
    q.push(`Trigger intent ${intent} and execute its configured action for this request.`);
  }
  for (let i = 0; i < 5; i++) {
    const intent = intentNames[i % Math.max(intentNames.length, 1)] ?? "out_of_scope";
    q.push(`Use skill ${skillName} first, then apply intent ${intent} follow-up if needed.`);
  }
  return Array.from(new Set(q));
}

export function buildTemplateBundle(
  params: GeneratedBundle["parameters"],
  useCase: string,
  notes?: string,
  orgContext?: { gptfyNamespace?: string }
): GeneratedBundle {
  const logPrefix = params.handlerClass.replace(/Handler$/, "").substring(0, 8).toUpperCase();
  const skillName = `${params.agentDeveloperName}_health_Check_Agent`;
  const handlerApex = buildHandlerApex(
    params.handlerClass,
    logPrefix,
    skillName,
    orgContext?.gptfyNamespace
  );

  const promptFile = `${skillName}_PromptCommand.json`;
  const promptContent = JSON.stringify(HEALTH_PROMPT_JSON, null, 2);

  const agentDescription = `${params.agentName}: ${useCase.slice(0, 200)}${useCase.length > 200 ? "…" : ""}`;

  const agentSystemPrompt = `You are ${params.agentName}, a Salesforce-focused assistant.

CORE RESPONSIBILITIES:
- Fulfill this use case precisely:
${useCase}
${notes ? `\nBUSINESS NOTES:\n${notes}\n` : ""}
- Keep answers concise, useful, and business-safe.

TOOL USAGE RULES (MANDATORY):
- For every Salesforce read or write, you MUST call a tool first.
- Never claim success unless tool JSON response includes success=true.
- If required inputs are missing, ask one clear follow-up question.
- In this starter bundle, your available skill is: ${skillName}.

ERROR-HANDLING POLICY:
- If a tool call fails, explain why and what user can do next.
- If no record is found, state that explicitly and ask for better filters.
- If access/permissions fail, tell the user to contact Salesforce admin.

RESPONSE STYLE:
- Use short sections: Outcome, Details, Next Step.
- Do not invent IDs, statuses, or completion results.
- If uncertain, say exactly what is unknown and what is needed.
`;

  const intentsConfigMd = `# ${params.agentName} — Intents (starter)

**Agent:** ${params.agentName}
**Total Intents:** 2 (minimum starter)

## ${params.agentDeveloperName}_greeting
**Trigger:** User opens chat or says hello.
**Actions:** Canned Response (welcome).

## ${params.agentDeveloperName}_out_of_scope
**Trigger:** User asks for something outside this agent's skills.
**Actions:** Canned Response (polite redirect).

> Extend with domain intents per docs/INTENT_ACTION_FRAMEWORK_GUIDE.md
`;

  const specMarkdown = `# Generated bundle (template)

## Use case
${useCase}

## Parameters
| Field | Value |
|-------|-------|
| Agent | ${params.agentName} |
| Developer name | ${params.agentDeveloperName} |
| Handler | ${params.handlerClass} |
| External prefix | ${params.externalIdPrefix} |

## Deploy steps
1. Copy \`classes/${params.handlerClass}.cls\` into \`force-app/main/default/classes/\` and deploy.
2. Copy \`use-cases/${params.agentDeveloperName}/\` into your repo.
3. Run \`Deploy-GptfyUseCasePipeline.ps1\` with matching parameters.

Namespace: package subscribers use \`ccai__\` / \`ccai_qa__\` on objects; unpackaged orgs often have no prefix.
`;

  const starterIntents = defaultIntentDeployPlan(
    params.agentDeveloperName,
    params.agentName
  );
  const sampleQueries = buildTemplateSampleQueries(
    skillName,
    starterIntents.map((x) => x.name)
  );

  return {
    version: 1,
    source: "template",
    parameters: params,
    handlerApex,
    handlerMetaXml: META_XML,
    agentDescription,
    agentSystemPrompt,
    intentsConfigMd,
    promptCommands: [{ fileName: promptFile, content: promptContent }],
    specMarkdown,
    fullConfigStubApex: buildFullConfigStub(params.agentName, params.handlerClass),
    intentDeployPlan: starterIntents,
    sampleQueries,
  };
}
